### PR TITLE
Issue64 durack1 source_id and CV cleanup

### LINKED ISSUE #18: Support missing value of 0 for "Nobs"-type ancillary variables
The following came up during a local test for using CMOR to process the two ancillary data fields "spco2Nobs" and "spco2Stderr" (by manually/locally adding variables for those two to my local "Omon" table): 

In accordance with "obs4MIPsDatasetRequirements_v1.2.pdf", I had set all "spco2Nobs" cells with missing data to 0, and had set the "missing_value" attribute for the "spco2Nobs" variable to 0 as well. 

After running the Nobs file through CMOR, the ncdump of the output contains:

```
int spco2Nobs(time, lat, lon) ;
    [...]
    spco2Nobs:history = "2016-09-29T22:01:40Z altered by CMOR: replaced missing value flag (0) with standard missing value (1e+20). 2016-09-29T22:01:40Z altered by CMOR: Converted type from \'f\' to \'i\'." ;
    spco2Nobs:missing_values = -2147483648 ;
    spco2Nobs:_FillValue = -2147483648 ;
```

On the upside, before converting zero to 1e20 (and converting that to -2147483648 in turn), CMOR recognized all missing cells correctly, so the information about what is missing is preserved, and just the meta-information affected. However, zero as a missing value should probably still be supported (or the "obs4MIPsDatasetRequirements_v1.2.pdf" be changed).

### LINKED ISSUE #64: source_id problems
I still have some problems with the ``source_id`` attribute (using the latest CMOR 3.2.6):

1. ``source_id`` is not validated by CMOR
2. ``src/writeJson.py`` does not include ``source_label`` and ``source_type`` defined within the ``source_id`` compound into the CV. I would suggest adding the following lines [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/src/writeJson.py#L668)

        obs4MIPs_CV['CV']['source_id'][key]['source_label'] = source_id_[key]['source_label']
        obs4MIPs_CV['CV']['source_id'][key]['source_type'] = source_id_[key]['source_type']
3. Even if I manually add ``source_type`` and ``source_label`` to the CV,

            "source_id":{
                "REMSS-PRW-6-6-0":{
                    "source":"REMSS PRW v6.6.0 (2017): Precipitable Water",
                    "source_label":"REMSS-PRW",
                    "source_type":"satellite_blended"
                }
            },

  CMOR doesn't recognize them.

### PR DESCRIPTION
**Pull request by durack1**
Fix #18
Fix #64 
Merge #63 

Awaiting changes in [`CMOR 3.2.6`](https://github.com/PCMDI/cmor/releases/tag/3.2.6) to land

@gleckler1 @taylor13 @dnadeau4

### CODE REVIEW

**Comment by durack1** [comment]
@dnadeau4 perfect, this is the output of the new file against `cmor-2017.08.24.3.2.6-np19py27hd0f7a31`:
```
// global attributes:
		:Conventions = "CF-1.7 ODS-2.0" ;
		:activity_id = "obs4MIPs" ;
		:contact = "RSS (support@remss.com)" ;
		:creation_date = "2017-08-24T23:46:24Z" ;
		:data_specs_version = "2.0.0" ;
		:external_variables = "areacella" ;
		:frequency = "mon" ;
		:further_info_url = "http://furtherinfo.es-doc.org/obs4MIPs.RSS.source_labelREMSS-PRW-6-6-0.prw" ;
		:grid = "2.5x2.5 degree latitude x longitude" ;
		:grid_label = "gn" ;
		:history = "2017-08-24T23:46:24Z CMOR rewrote data to be consistent with CF standards and  requirements." ;
		:institution = "Remote Sensing Systems, Santa Rosa, CA 95401, USA" ;
		:institution_id = "RSS" ;
		:nominal_resolution = "250 km" ;
		:product = "observations" ;
		:realm = "atmos" ;
		:region = "global" ;
		:source = "REMSS PRW 6.6.0 (2017): Precipitable Water" ;
		:source_id = "REMSS-PRW-6-6-0" ;
		:source_label = "REMSS-PRW" ;
		:source_type = "satellite_blended" ;
		:table_id = "obs4MIPs_Amon" ;
		:table_info = "Creation Date:(24 August 2017) MD5:c607684c407d8bde132ba2037909a681" ;
		:title = "PRW V6.6.0 prepared for obs4MIPs (ODS-v2.0.0)" ;
		:tracking_id = "hdl:21.14102/cff2f281-9f3d-47f1-b4b1-c96a4e7c2a75" ;
		:variable_id = "prw" ;
		:variant_info = "Best Estimate" ;
		:variant_label = "BE" ;
		:license = "Data in this file produced by <Your Centre Name> is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Use of the data must be acknowledged following guidelines found at <a URL maintained by you>. Further information about this data, including some limitations, can be found via <some URL maintained by you>" ;
		:cmor_version = "3.2.6" ;
}
```
@gleckler1 @taylor13 if you can take a quick peek at the above, I will merge this ASAP..

**Comment by durack1** [comment]
@taylor13 there is one issue, `further_info_url` which has a value of:
```
:further_info_url = "http://furtherinfo.es-doc.org/obs4MIPs.RSS.source_labelREMSS-PRW-6-6-0.prw" ;
```
Because the input template is:
```
"_further_info_url_tmpl":       "http://furtherinfo.es-doc.org/<activity_id><institution_id><source_label><source_id><variable_id>",
```
Seems like `source_label` and `source_id` duplicates content..

**Comment by dnadeau4** [comment]
Remove your `further_info_url` from you Control Vocabulary `required_global_attributes` list. 

There is a new push of 3.2.6 that should fix this problem in a couple of hours for OSX.

**Comment by durack1** [comment]
@dnadeau4 I've just hit this error with the nightly:
```
(cmor326Nightly170825) bash-3.2$ python runCmorDemo.py 
/Users/durack1/anaconda2/envs/cmor326Nightly170825/lib/python2.7/site-packages/cdms2/axis.py:769: UserWarning: genutil module not present, was not able to determine if axis is level based on units
  "genutil module not present, was not able to determine if axis is level based on units")

C Traceback:
! In function: cmor_check_monotonic
! called from: cmor_write_var_to_file
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: axis time (table: obs4MIPs_Amon) has non monotonic
! bounds values : 0.000000, 0.000000, 31.000000
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "runCmorDemo.py", line 55, in <module>
    cmor.write(varid,values,time_vals=time[:],time_bnds=time.getBounds()) ; # Write variable with time axis
  File "/Users/durack1/anaconda2/envs/cmor326Nightly170825/lib/python2.7/site-packages/cmor/pywrapper.py", line 795, in write
    time_vals, time_bnds, store_with)
_cmor.CMORError: Problem with 'cmor.write'. Please check the logfile (if defined).
```
Any tips what has changed to now provide this error?

**Comment by taylor13** [comment]
Denis and I modified CMOR to check bounds to trap the error identified in https://github.com/PCMDI/cmor/issues/148 .  I have just reviewed what we did, and it looks correct.  What values are you passing as time bounds in your test case?  CMOR seems to receive and analyze: (0., ??, 0., ??, 31. ....)    The ?? means that the error message only reports every-other bound value.  It looks like the first two lower time bounds are both 0.

Here's the relevant piece of code:

```
 if (isbounds == 1) {
        for (i = 0; i < length / 2 - 2; i++) {
            if (((values[2 * i] - values[2 * i + 2])
                 * (values[2 * i + 2] - values[2 * i + 4])) < 0.) {
                if (cmor_isLongitude(refaxis) == 1) {
                    treatlon = 1;
                } else {
                    snprintf(msg, CMOR_MAX_STRING,
                             "axis %s (table: %s) has non monotonic\n! "
                             "bounds values : %lf, %lf, %lf", name,
                             cmor_tables[cmor_axes[axis_id].
                                         ref_table_id].szTable_id,
                             values[2 * i], values[2 * i + 2],
                             values[2 * i + 4]);
                    if (refaxis->climatology == 0) {
                        cmor_handle_error(msg, CMOR_CRITICAL);
                    } else {
                        cmor_handle_error(msg, CMOR_WARNING);
                    }
                }
            }
}
```

**Comment by durack1** [comment]
@taylor13 @dnadeau4 I think you've introduced a bug, the demo file that I've been using seems to have valid data:
```
time
Out[16]: 
   id: months
   units:  months since 1987-1-1 0:0:0
   Length: 24
   First:  0
   Last:   23
   Other axis attributes:
      long_name: time
      realtopology: linear
   Python id:  0x11ef9ed10

time[:]
Out[17]: 
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)

time.getBounds()
Out[18]: 
array([[ -0.5,   0.5],
       [  0.5,   1.5],
       [  1.5,   2.5],
       [  2.5,   3.5],
       [  3.5,   4.5],
       [  4.5,   5.5],
       [  5.5,   6.5],
       [  6.5,   7.5],
       [  7.5,   8.5],
       [  8.5,   9.5],
       [  9.5,  10.5],
       [ 10.5,  11.5],
       [ 11.5,  12.5],
       [ 12.5,  13.5],
       [ 13.5,  14.5],
       [ 14.5,  15.5],
       [ 15.5,  16.5],
       [ 16.5,  17.5],
       [ 17.5,  18.5],
       [ 18.5,  19.5],
       [ 19.5,  20.5],
       [ 20.5,  21.5],
       [ 21.5,  22.5],
       [ 22.5,  23.5]])
```
The first bounds value is negative which is getting reset to 0.

**Comment by taylor13** [comment]
Is that a file you read in?  It has invalid units because "months since" is not a unit (the month increments are not all equal).  Before you call CMOR, you must convert the month bounds and the axis to "days since".    Perhaps cdtime is able to convert from units of "months since" to "days since" and if CMOR invokes cdtime to change the units, then perhaps the problem is with cdtime.  CMOR should not attempt to write a time axis that has so-called "units" of "months since".  Try defining a correct time axis  (say units of "days since 1987-1-1 0:0:0") with  bounds of 0., 31.,  31., 59.,  59., 90., .... and coordinate values half way between each pair of bounds.  CMOR should work then.

perhaps Denis or Charles know what cdtime does to try to convert axes and bounds with "units" of "months since"

**Comment by durack1** [comment]
@taylor13 this is the obs4MIPs demo file, which checks out fine on the CF-checker, at least for the time dimension:
```
File name:      rss_ssmi_prw_v06.6-demo.nc
Output of CF-Checker follows...
CHECKING NetCDF FILE: /tmp/4819.nc
=====================
WARNING: Cannot determine CF version from the Conventions attribute; checking against latest CF version: CF-1.6
Using CF Checker Version 2.0.9
Checking against CF Version CF-1.6
Using Standard Name Table Version 46 (2017-07-25T09:41:29Z)
Using Area Type Table Version 6 (22 February 2017)
WARNING (2.6.1): No 'Conventions' attribute present
------------------
Checking variable: longitude_bounds
------------------
------------------
Checking variable: months
------------------
------------------
Checking variable: prw
------------------
------------------
Checking variable: longitude
------------------
ERROR (3.1): Invalid units:  degrees east
------------------
Checking variable: bounds_months
------------------
------------------
Checking variable: latitude
------------------
ERROR (3.1): Invalid units:  degrees north
------------------
Checking variable: latitude_bounds
------------------
ERRORS detected: 2
WARNINGS given: 2
INFORMATION messages: 0
```

**Comment by durack1** [comment]
Ok thanks to @dnadeau4 and some kludging to fix the bounds of the `month since` calendar for the demo, this is the current output:
```
(cmor326Nightly170825) bash-3.2$ ncdump -h demo/obs4MIPs/RSS/REMSS-PRW-6-6-0/obs4MIPs_Amon/prw/gn/v20170825/prw_obs4MIPs_Amon_REMSS-PRW-6-6-0_BE_gn_198701-198812.nc 
netcdf prw_obs4MIPs_Amon_REMSS-PRW-6-6-0_BE_gn_198701-198812 {
dimensions:
	time = UNLIMITED ; // (24 currently)
	lat = 72 ;
	lon = 144 ;
	bnds = 2 ;
variables:
...
// global attributes:
		:Conventions = "CF-1.7 ODS-2.0" ;
		:activity_id = "obs4MIPs" ;
		:contact = "RSS (support@remss.com)" ;
		:creation_date = "2017-08-25T23:55:20Z" ;
		:data_specs_version = "2.0.0" ;
		:external_variables = "areacella" ;
		:frequency = "mon" ;
		:further_info_url = "http://furtherinfo.es-doc.org/obs4MIPs.RSS.REMSS-PRW.REMSS-PRW-6-6-0.prw" ;
		:grid = "2.5x2.5 degree latitude x longitude" ;
		:grid_label = "gn" ;
		:history = "2017-08-25T23:55:20Z CMOR rewrote data to be consistent with CF standards and  requirements." ;
		:institution = "Remote Sensing Systems, Santa Rosa, CA 95401, USA" ;
		:institution_id = "RSS" ;
		:nominal_resolution = "250 km" ;
		:product = "observations" ;
		:realm = "atmos" ;
		:region = "global" ;
		:source = "REMSS PRW 6.6.0 (2017): Precipitable Water" ;
		:source_id = "REMSS-PRW-6-6-0" ;
		:source_label = "REMSS-PRW" ;
		:source_type = "satellite_blended" ;
		:table_id = "obs4MIPs_Amon" ;
		:table_info = "Creation Date:(25 August 2017) MD5:889c9ea94f674851ad9f5ef31e8f4c41" ;
		:title = "PRW V6.6.0 prepared for obs4MIPs (ODS-v2.0.0)" ;
		:tracking_id = "hdl:21.14102/a9758877-3971-4a54-a7ad-24ce13dcf774" ;
		:variable_id = "prw" ;
		:variant_info = "Best Estimate" ;
		:variant_label = "BE" ;
		:license = "Data in this file produced by <Your Centre Name> is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Use of the data must be acknowledged following guidelines found at <a URL maintained by you>. Further information about this data, including some limitations, can be found via <some URL maintained by you>" ;
		:cmor_version = "3.2.6" ;
}
```

This looks fine to me so I will update the demo in the PR and merge immediately

**Comment by taylor13** [comment]
What's the rest of the file look like.  In particular the time axis and its bounds?

**Comment by durack1** [comment]
@taylor13 here you go:
```
% ncdump -t obs4MIPs-cmor-tables/demo/demo/obs4MIPs/RSS/REMSS-PRW-6-6-0/obs4MIPs_Amon/prw/gn/v20170825/prw_obs4MIPs_Amon_REMSS-PRW-6-6-0_BE_gn_198701-198812.nc | more

netcdf prw_obs4MIPs_Amon_REMSS-PRW-6-6-0_BE_gn_198701-198812 {
dimensions:
        time = UNLIMITED ; // (24 currently)
        lat = 72 ;
        lon = 144 ;
        bnds = 2 ;
variables:
        double time(time) ;
                time:bounds = "time_bnds" ;
                time:units = "days since 1987-1-1 0:0:0" ;
                time:calendar = "gregorian" ;
                time:axis = "T" ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
        double time_bnds(time, bnds) ;
        double lat(lat) ;
                lat:bounds = "lat_bnds" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
                lat:long_name = "latitude" ;
                lat:standard_name = "latitude" ;
        double lat_bnds(lat, bnds) ;
        double lon(lon) ;
                lon:bounds = "lon_bnds" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
                lon:long_name = "longitude" ;
                lon:standard_name = "longitude" ;
        double lon_bnds(lon, bnds) ;
        float prw(time, lat, lon) ;
                prw:standard_name = "atmosphere_water_vapor_content" ;
                prw:long_name = "Water Vapor Path" ;
                prw:comment = "vertically integrated through the atmospheric column" ;
                prw:units = "kg m-2" ;
                prw:cell_methods = "area: time: mean" ;
                prw:cell_measures = "area: areacella" ;
                prw:missing_value = 1.e+20f ;
                prw:_FillValue = 1.e+20f ;

// global attributes:
                :_NCProperties = "version=1|netcdflibversion=4.4.1|hdf5libversion=1.8.17" ;
                :Conventions = "CF-1.7 ODS-2.0" ;
                :activity_id = "obs4MIPs" ;
                :contact = "RSS (support@remss.com)" ;
                :creation_date = "2017-08-25T23:55:20Z" ;
                :data_specs_version = "2.0.0" ;
                :external_variables = "areacella" ;
                :frequency = "mon" ;
                :further_info_url = "http://furtherinfo.es-doc.org/obs4MIPs.RSS.REMSS-PRW.REMSS-PRW-6-6-0.prw" ;
                :grid = "2.5x2.5 degree latitude x longitude" ;
                :grid_label = "gn" ;
                :history = "2017-08-25T23:55:20Z CMOR rewrote data to be consistent with CF standards and  requirements." ;
                :institution = "Remote Sensing Systems, Santa Rosa, CA 95401, USA" ;
                :institution_id = "RSS" ;
                :nominal_resolution = "250 km" ;
                :product = "observations" ;
                :realm = "atmos" ;
                :region = "global" ;
                :source = "REMSS PRW 6.6.0 (2017): Precipitable Water" ;
                :source_id = "REMSS-PRW-6-6-0" ;
                :source_label = "REMSS-PRW" ;
                :source_type = "satellite_blended" ;
                :table_id = "obs4MIPs_Amon" ;
                :table_info = "Creation Date:(25 August 2017) MD5:889c9ea94f674851ad9f5ef31e8f4c41" ;
                :title = "PRW V6.6.0 prepared for obs4MIPs (ODS-v2.0.0)" ;
                :tracking_id = "hdl:21.14102/a9758877-3971-4a54-a7ad-24ce13dcf774" ;
                :variable_id = "prw" ;
                :variant_info = "Best Estimate" ;
                :variant_label = "BE" ;
                :license = "Data in this file produced by <Your Centre Name> is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Use of the data must be acknowledged following guidelines found at <a URL maintained by you>. Further information about this data, including some limitations, can be found via <some URL maintained by you>" ;
                :cmor_version = "3.2.6" ;
data:

 time = "1987-01-16 12", "1987-02-15", "1987-03-16 12", "1987-04-16", 
    "1987-05-16 12", "1987-06-16", "1987-07-16 12", "1987-08-16 12", 
    "1987-09-16", "1987-10-16 12", "1987-11-16", "1987-12-16 12", 
    "1988-01-16 12", "1988-02-15 12", "1988-03-16 12", "1988-04-16", 
    "1988-05-16 12", "1988-06-16", "1988-07-16 12", "1988-08-16 12", 
    "1988-09-16", "1988-10-16 12", "1988-11-16", "1988-12-16 12" ;

 time_bnds =
  0, 31,
  31, 59,
  59, 90,
  90, 120,
  120, 151,
  151, 181,
  181, 212,
  212, 243,
  243, 273,
  273, 304,
  304, 334,
  334, 365,
  365, 396,
  396, 425,
  425, 456,
  456, 486,
  486, 517,
  517, 547,
  547, 578,
  578, 609,
  609, 639,
  639, 670,
  670, 700,
  700, 731 ;

 lat = -88.75, -86.25, -83.75, -81.25, -78.75, -76.25, -73.75, -71.25, 
    -68.75, -66.25, -63.75, -61.25, -58.75, -56.25, -53.75, -51.25, -48.75, 
    -46.25, -43.75, -41.25, -38.75, -36.25, -33.75, -31.25, -28.75, -26.25, 
    -23.75, -21.25, -18.75, -16.25, -13.75, -11.25, -8.75, -6.25, -3.75, 
    -1.25, 1.25, 3.75, 6.25, 8.75, 11.25, 13.75, 16.25, 18.75, 21.25, 23.75, 
    26.25, 28.75, 31.25, 33.75, 36.25, 38.75, 41.25, 43.75, 46.25, 48.75, 
    51.25, 53.75, 56.25, 58.75, 61.25, 63.75, 66.25, 68.75, 71.25, 73.75, 
    76.25, 78.75, 81.25, 83.75, 86.25, 88.75 ;

 lat_bnds =
  -90, -87.5,
  -87.5, -85,
  -85, -82.5,
  -82.5, -80,
  -80, -77.5,
  -77.5, -75,
  -75, -72.5,
  -72.5, -70,
  -70, -67.5,
  -67.5, -65,
  -65, -62.5,
  -62.5, -60,
  -60, -57.5,
  -57.5, -55,
  -55, -52.5,
  -52.5, -50,
  -50, -47.5,
  -47.5, -45,
  -45, -42.5,
  -42.5, -40,
  -40, -37.5,
  -37.5, -35,
  -35, -32.5,
  -32.5, -30,
  -30, -27.5,
  -27.5, -25,
  -25, -22.5,
  -22.5, -20,
  -20, -17.5,
  -17.5, -15,
  -15, -12.5,
  -12.5, -10,
  -10, -7.5,
  -7.5, -5,
  -5, -2.5,
  -2.5, 0,
  0, 2.5,
  2.5, 5,
  5, 7.5,
  7.5, 10,
  10, 12.5,
  12.5, 15,
  15, 17.5,
  17.5, 20,
  20, 22.5,
  22.5, 25,
  25, 27.5,
  27.5, 30,
  30, 32.5,
  32.5, 35,
  35, 37.5,
  37.5, 40,
  40, 42.5,
  42.5, 45,
  45, 47.5,
  47.5, 50,
  50, 52.5,
  52.5, 55,
  55, 57.5,
  57.5, 60,
  60, 62.5,
  62.5, 65,
  65, 67.5,
  67.5, 70,
  70, 72.5,
  72.5, 75,
  75, 77.5,
  77.5, 80,
  80, 82.5,
  82.5, 85,
  85, 87.5,
  87.5, 90 ;

 lon = 1.25, 3.75, 6.25, 8.75, 11.25, 13.75, 16.25, 18.75, 21.25, 23.75, 
    26.25, 28.75, 31.25, 33.75, 36.25, 38.75, 41.25, 43.75, 46.25, 48.75, 
    51.25, 53.75, 56.25, 58.75, 61.25, 63.75, 66.25, 68.75, 71.25, 73.75, 
    76.25, 78.75, 81.25, 83.75, 86.25, 88.75, 91.25, 93.75, 96.25, 98.75, 
    101.25, 103.75, 106.25, 108.75, 111.25, 113.75, 116.25, 118.75, 121.25, 
    123.75, 126.25, 128.75, 131.25, 133.75, 136.25, 138.75, 141.25, 143.75, 
    146.25, 148.75, 151.25, 153.75, 156.25, 158.75, 161.25, 163.75, 166.25, 
    168.75, 171.25, 173.75, 176.25, 178.75, 181.25, 183.75, 186.25, 188.75, 
    191.25, 193.75, 196.25, 198.75, 201.25, 203.75, 206.25, 208.75, 211.25, 
    213.75, 216.25, 218.75, 221.25, 223.75, 226.25, 228.75, 231.25, 233.75, 
    236.25, 238.75, 241.25, 243.75, 246.25, 248.75, 251.25, 253.75, 256.25, 
    258.75, 261.25, 263.75, 266.25, 268.75, 271.25, 273.75, 276.25, 278.75, 
    281.25, 283.75, 286.25, 288.75, 291.25, 293.75, 296.25, 298.75, 301.25, 
    303.75, 306.25, 308.75, 311.25, 313.75, 316.25, 318.75, 321.25, 323.75, 
    326.25, 328.75, 331.25, 333.75, 336.25, 338.75, 341.25, 343.75, 346.25, 
    348.75, 351.25, 353.75, 356.25, 358.75 ;

 lon_bnds =
  0, 2.5,
  2.5, 5,
  5, 7.5,
  7.5, 10,
  10, 12.5,
  12.5, 15,
  15, 17.5,
  17.5, 20,
  20, 22.5,
  22.5, 25,
  25, 27.5,
  27.5, 30,
  30, 32.5,
  32.5, 35,
  35, 37.5,
  37.5, 40,
  40, 42.5,
  42.5, 45,
  45, 47.5,
  47.5, 50,
  50, 52.5,
  52.5, 55,
  55, 57.5,
  57.5, 60,
  60, 62.5,
  62.5, 65,
  65, 67.5,
  67.5, 70,
  70, 72.5,
  72.5, 75,
  75, 77.5,
  77.5, 80,
  80, 82.5,
  82.5, 85,
  85, 87.5,
  87.5, 90,
  90, 92.5,
  92.5, 95,
  95, 97.5,
  97.5, 100,
  100, 102.5,
  102.5, 105,
  105, 107.5,
  107.5, 110,
  110, 112.5,
  112.5, 115,
  115, 117.5,
  117.5, 120,
  120, 122.5,
  122.5, 125,
  125, 127.5,
  127.5, 130,
  130, 132.5,
  132.5, 135,
  135, 137.5,
  137.5, 140,
  140, 142.5,
  142.5, 145,
  145, 147.5,
  147.5, 150,
  150, 152.5,
  152.5, 155,
  155, 157.5,
  157.5, 160,
  160, 162.5,
  162.5, 165,
  165, 167.5,
  167.5, 170,
  170, 172.5,
  172.5, 175,
  175, 177.5,
  177.5, 180,
  180, 182.5,
  182.5, 185,
  185, 187.5,
  187.5, 190,
  190, 192.5,
  192.5, 195,
  195, 197.5,
  197.5, 200,
  200, 202.5,
  202.5, 205,
  205, 207.5,
  207.5, 210,
  210, 212.5,
  212.5, 215,
  215, 217.5,
  217.5, 220,
  220, 222.5,
  222.5, 225,
  225, 227.5,
  227.5, 230,
  230, 232.5,
  232.5, 235,
  235, 237.5,
  237.5, 240,
  240, 242.5,
  242.5, 245,
  245, 247.5,
  247.5, 250,
  250, 252.5,
  252.5, 255,
  255, 257.5,
  257.5, 260,
  260, 262.5,
  262.5, 265,
  265, 267.5,
  267.5, 270,
  270, 272.5,
  272.5, 275,
  275, 277.5,
  277.5, 280,
  280, 282.5,
  282.5, 285,
  285, 287.5,
  287.5, 290,
  290, 292.5,
  292.5, 295,
  295, 297.5,
  297.5, 300,
  300, 302.5,
  302.5, 305,
  305, 307.5,
  307.5, 310,
  310, 312.5,
  312.5, 315,
  315, 317.5,
  317.5, 320,
  320, 322.5,
  322.5, 325,
  325, 327.5,
  327.5, 330,
  330, 332.5,
  332.5, 335,
  335, 337.5,
  337.5, 340,
  340, 342.5,
  342.5, 345,
  345, 347.5,
  347.5, 350,
  350, 352.5,
  352.5, 355,
  355, 357.5,
  357.5, 360 ;
```

**Comment by Funkensieper** [comment]
I tested the most recent tables with the CMOR master: works fine! Only CMOR does still not validate ``source_id``.

**Comment by taylor13** [comment]
@Funkensieper When you say "CMOR does not validated source_id" do you mean:
1) CMOR raises an error?
2) CMOR doesn't check that the value assigned to source_id is correct?

(Apologies if the answer is obvious.)

**Comment by Funkensieper** [comment]
CMOR doesn't check that the value assigned to source_id is correct.

**Pull request merged**
