### PR TITLE
Add Amon variable pme

### LINKED ISSUE #72: New Amon Variable: Freshwater Flux
After the remaining DWD variables have been signed off, we would like to propose a new Amon variable for Freshwater Flux:

        "fr":{
            "cell_measures":"area: areacella",
            "cell_methods":"area: time: mean",
            "comment":"Difference of Precipitation and Evaporation",
            "dimensions":"longitude latitude time",
            "frequency":"mon",
            "long_name":"Freshwater Flux",
            "ok_max_mean_abs":"",
            "ok_min_mean_abs":"",
            "out_name":"fr",
            "positive":"",
            "standard_name":"",
            "type":"real",
            "units":"kg m-2 s-1",
            "valid_max":"",
            "valid_min":""
        }

### PR DESCRIPTION
**Pull request by durack1**
Fix #72 

@Funkensieper there are some amendments to your final version. `"cell_measures":"area: areacella"` will prompt the generation of an `external_variable` attribute which suggests an `areacella` file will also be written - in ODS-2.1 this is not requested.

### CODE REVIEW

**Comment by Funkensieper** [comment]
That's fine, I just copied ``cell_measures`` from another variable anyway. But it should be ``cell_methods=area:time:mean``, at least for our dataset.

**Comment by durack1** [comment]
@Funkensieper thanks for checking, I just updated the obs4MIPs registered variable to maintain a format consistency, your `pme` is as before with `"cell_methods":"area: mean time: mean"` which accurately captures the correct info

**Comment by Funkensieper** [comment]
Ah, no that was a misunderstanding. The CCI variables have ``cell_methods=area: time: mean`` because the mean is computed over all observations which were sampled into a certain gridbox over the course of one month. The other monthly mean variables (CLARA, pme) are computed from daily means so ``cell_methods=area: mean time: mean`` is more appropriate. Maybe it makes sense to give the user the opportunity to overwrite the ``cell_methods`` of a variable?

**Comment by durack1** [comment]
@Funkensieper apologies, it wasn't clear to me if changes are required, we currently have in [PCMDI/obs4MIPs-cmor-tables/Tables/obs4MIPs_Amon.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L834-L850):
```
        "pme":{
            "cell_measures":"",
            "cell_methods":"area: mean time: mean",
            "comment":"Net flux of water (in all phases) between the atmosphere and underlying surface including vegetation), mainly resulting from the difference of precipitation and evaporation",
            "dimensions":"longitude latitude time",
            "frequency":"mon",
            "long_name":"Surface Downward Freshwater Flux",
            "ok_max_mean_abs":"",
            "ok_min_mean_abs":"",
            "out_name":"pme",
            "positive":"",
            "standard_name":"surface_downward_water_flux",
            "type":"real",
            "units":"kg m-2 s-1",
            "valid_max":"",
            "valid_min":""
},
```
Did we need to tweak this registration?

**Comment by Funkensieper** [comment]
Yes, pme's cell methods should be changed to ``area:time:mean``. Sorry, I mixed that up in my previous comment. Besides, the cell methods of  ``clCCI, cltCCI, clwCCI, clwtCCI, pctCCI`` were accidentally changed by commit 9bbb576108ae602b798dc9bf342cd5b4c1dcbfd8 . The correct cell_methods here are ``area:time:mean``.

**Pull request merged**
