### PR TITLE
Issue48 funkensieper add new Amon variables

### PR DESCRIPTION
**Pull request by durack1**
@gleckler1 @taylor13 @Funkensieper

This PR pulls the variable request out of #46, it also updates all tables to be consistent with the 01.00.12 release of the data request. There is some ongoing discussion of the variable names in #48 regarding the variable names

### CODE REVIEW

**Comment by durack1** [comment]
`DWD` registration was completed in May #39

**Comment by Funkensieper** [comment]
We also have ancillary variables (nobs, std. deviation) for some of these variables. Do they have to be added to the tables as well? Currently we're generating ancillary tables (based on the obs4MIPs table) to make CMOR rewrite the ancillary variables.

**Comment by durack1** [comment]
@Funkensieper good question, dealing with the ancillary fields (stdev, Nobs etc) should be dealt with at a global level in my opinion. This will avoid having to generate a new entry for each and every variable that requires these

**Comment by Funkensieper** [comment]
In principle I agree. However, I had problems deriving the cell methods of an ancillary variable from the cell methods of its corresponding primary variable. For example if the primary variable has ``cell_methods=area: mean time: mean``, but the standard deviation is computed over the timesteps only, the ancillary variable should have ``cell_methods=time: standard_deviation``. I think this information has to be supplied by the data provider.

**Comment by durack1** [comment]
@Funkensieper I think we should redirect discussions back into #50, as this PR will be merged (and closed)

**Pull request merged**
