### PR TITLE
Add 'further_info_url' and 'source_label' to input .json metadata

### PR DESCRIPTION
**Pull request by manaster**

### CODE REVIEW

**Comment by manaster** [comment]
@gleckler1 this branch was made to add 'further_info_url' and 'source_label' metadata to CERES V4.2, GPCP V3.2, and RSS PRW V7.2 input .jsons.  You should be able to merge it into 'master' without any hassle.

**Comment by manaster** [comment]
@gleckler1 pinging you again to see if it is ok to merge this branch.  I created it to add "further_info_url" and "source_label" to the .json metadata for CERES V4.2, GPCP V3.2, and RSS PRW V7.2.

**Comment by gleckler1** [comment]
@manaster  top level readme on master was just updated.   Have you merged with that?

**Comment by manaster** [comment]
@gleckler1 just rebased this branch with 'master', so now it should contain the updated README

**Pull request merged**
