### PR TITLE
157 pjg ncei additions

### PR DESCRIPTION
**Pull request by gleckler1**
@JimBiardCics @scott-stevens @durack1 @taylor13 @sahsakames   JB I've entered your proposed new Registered Content on this PR and will merge once we've confirmed all is copacetic.   A few comments...

Having seperate files for Arctic and Antarctic siconc I believe is inconsistant with the CMIP data structure and therefor also ODS2.1 as we don't have a mechanism for distinguishing between them in the filename and/or directory template (https://docs.google.com/document/d/1FXXBhUh71Hjus557ZTD3EKPi_2zxeLvi1aICXOjVYPc/edit#heading=h.d9zuwrx4mmrd).   We can  probably kludge it in the ESGF publication process but we want to avoid that if possible.   We've had discussions about this before (which currently escape me).  Do the siconc obs need to be reported on seperate grids?  I think I know the answer but looking to be re-educated.  

FYI, a decision has been made about the Nobs, Stderr and other possible additional data that a provider may want to include with their obs4MIPs product.   Efforts are underway to demonstrate the next-gen obs4MIPs CoG site designed to be consistent with CMIP6.   In addition to new search attributes, it will be possible to provide free form "Supplemental Information" as additional data and/or metadata bundled as a zip that is directly associated with a dataset found via an ESGF search.   Between PCMDI and JPL we'll have a prototype of this by summer and this will demonstrate how Nobs, etc can be attached to the data.   In otherwords, at this time we are not attempting to control vocaculary for these ancillary data.

### CODE REVIEW

**Comment by JimBiardCics** [comment]
@gleckler1, @durack1 The SeaIce product is on a pair of Polar Stereographic projection grids (one for north and one for south). This data is poorly suited for a lat/lon grid because it is all about the poles. I don't know of a good way to store this in a single variable in a single file.

**Comment by gleckler1** [comment]
@JimBiardCics @durack1 @taylor13  That is the answer I was expecting.   A simple solution may be to have two RC entries, one with source_name = 'NOAA NCEI Arctic SeaIce' and the other source_name = 'NOAA NCEI Antarctic SeaIce'.   While this may seem a little awkward, we do expect this situation to be something of a special case, and this path would require no changes to ODS nor how you are handling the data.   We'll have a PCMDI huddle and get back to you mid week.   Any thoughts?

**Comment by JimBiardCics** [comment]
I've got no problem with that. I guess there's no better option, considering that the variable is the same in both cases. That is, there's no way to make a single source that contains the same variable with two different geographic coverages.

**Comment by durack1** [comment]
@gleckler1 @JimBiardCics in some way this is being dealt with by including the `table_id` in the path and the filename in CMIP6, as there are separate tables for Greenland (e.g. [`CMIP6_IfxGre.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_IfxGre.json)) vs Antarctica (e.g. [`CMIP6_IfxAnt.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_IfxAnt.json))

We could define two grid labels to deal with this - so `gn` for the "native", and `grN`, that is an option

**Comment by gleckler1** [comment]
@JimBiardCics @durack1  Thats an interesting idea as grid_label is part of ODS2.1 filename and DRS ... I see some CMIP6 options that may be a good fit (gr1a and gr1g below).   Lets consult with @taylor13 before making a decision about this.  

       "gna":"data reported on a native grid in the region of Antarctica",
        "gng":"data reported on a native grid in the region of Greenland",
        "gnz":"zonal mean data reported on a model's native latitude grid",
        "gr":"regridded data reported on the data provider's preferred target grid",
        "gr1":"regridded data reported on a grid other than the native grid and other than the preferred target grid",
        "gr1a":"regridded data reported in the region of Antarctica on a grid other than the native grid and other than the preferred target grid",
"gr1g":"regridded data reported in the region of Greenland on a grid other than the native grid and other than the preferred target grid",

**Comment by durack1** [comment]
@gleckler1 exactly, or even the native variants `gna` and `gng` above

**Comment by JimBiardCics** [comment]
@gleckler1 @taylor13 @durack1 I think they are hemispheric. They are polar stereographic grids that are square in their CRSs. They are centered on their respective poles, and extend at the corners to 31 degrees north/south.

**Comment by durack1** [comment]
@gleckler1 this is likely another one that needs closing.. It's now WAAAAAYY old

**Pull request closed without merging**
