### PR TITLE
Sync CV with most recent data specifications

### PR DESCRIPTION
**Pull request by Funkensieper**
I asked @gleckler1 how I could help speed things up a bit and he encouraged me to send a PR. This one adresses #40 .

- Update required_global_attributes (including "variant_label"
  as it also appears in the filename)
- Fixate value of "product" attribute to "observations"
- Add new variables to CV:
      * activity_id
      * further_info_url
      * source_type
      * source_version_number
      * tracking_id
      * variant_label

I didn't include changes in ``demo1/obs4MIPs_CMOR_tables/*.json`` as they seem to be placeholders. If ``source_id`` and ``source`` are indeed registered content, I can add them to the CV as well.

### CODE REVIEW

**Comment by durack1** [comment]
@Funkensieper thanks for this! I note that a number of the included new CV entries (such as `variant_label`) are not up-to-date with the current working version of the obs4MIPs data conventions (see https://goo.gl/jVZsQl) so this PR will need to be considerably amended once these are finalised

**Comment by Funkensieper** [comment]
Strange, this is exactly the document I was working with (last update: June 13). So either I don't have access to the most recent version or I didn't understand it correctly :D Could you please point out the discrepancies in more detail? Regarding ``variant_label`` I think the document is ambiguous. There are the examples in the table but also note 5. I used the latter as it is much more detailed.

**Comment by durack1** [comment]
@Funkensieper you're right, the obs4MIPs document is building on the CMIP6 specifications which are currently being finalized. The `variant_label` noted as `r1i1p1f1` relates to a model simulation (see Appendix 1 in http://goo.gl/v1drZl), and so is not relevant (in the CMIP6 form) to obs4MIPs. #40 was intended as a placeholder, to be finalized once the obs4MIPs data conventions (https://goo.gl/jVZsQl) are finalized. We're hoping within the next couple of weeks.

**Comment by Funkensieper** [comment]
@durack1 Thanks for the clarification. So we'll have to wait for the conventions to be finalized. In the meantime I'll keep adding commits if I have further ideas.

**Comment by durack1** [comment]
@Funkensieper this should be solved by #52 which was just merged. It brings the demo in line with the current specifications detailed at https://goo.gl/jVZsQl

Consequently, I am closing this PR.

**Pull request closed without merging**
